# Generated by Django 6.0.1 on 2026-01-13 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_repairorder_options_repairorder_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(default='payment.success', help_text='e.g., payment.success, payment.failed', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payload', models.JSONField(default=dict, help_text='Raw webhook payload')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='orders.repairorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='payments_pa_event_i_62e0c5_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_c66eca_idx')],
            },
        ),
    ]
